# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flutter_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  flutter_application_path = '../my_flutter'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

  # Pods for Flutter_iOS

end
